### ISSUE TITLE
Rust GNU toolchain in windows not able to compile

### ISSUE THREAD

**Issue by selvavm** [rust-math/intel-mkl-src#59]
I am using NDArray Linalg (https://github.com/rust-ndarray/ndarray-linalg) with intel-mkl-static feature. It is working in msvc toolchain perfectly.

However, when I switch to GNU toolchain, I am getting below error,
```
could not find native static library `mkl_intel_lp64`, perhaps an -L flag is missing?
```

**Comment by aleon1138** [comment]
I just ran into this same problem just now. It seems you cant build a static library with iomp5. So for example:

```toml
[dependencies]
intel-mkl-src = { version = "0.6", default-features = false, features = ["mkl-static-ilp64-iomp"] }
```

Will fail to compile, but `mkl-static-ilp64-seq` or `mkl-dynamic-ilp64-iomp` will work just fine. This seems to be an issue with the build script somewhere.
